class AddColumnVeryToClinicals < ActiveRecord::Migration[5.0]
  def change
  	add_column :clinicals, :lugar, :string
  	add_column :clinicals, :fecha, :date
  	add_column :clinicals, :apellido, :string
  	add_column :clinicals, :nombre, :string
  	add_column :clinicals, :clase, :string
  	add_column :clinicals, :edad, :string
  	add_column :clinicals, :dni, :string
  	add_column :clinicals, :nacionalidad, :string
  	add_column :clinicals, :estado_civil, :string
  	add_column :clinicals, :tarea_designado, :string 
  	add_column :clinicals, :categoria, :string
  	add_column :clinicals, :peso, :string
  	add_column :clinicals, :estatura, :string
  	add_column :clinicals, :pulso, :string
  	add_column :clinicals, :temperatura, :string
  	add_column :clinicals, :presion_arterial_max, :string
  	add_column :clinicals, :presion_arterial_min,  :string
  	add_column :clinicals, :antec_heriditarios_personales, :string
  	add_column :clinicals, :estado_gral_morfologia_nutricion, :string
  	add_column :clinicals, :sistema_oseo_art_muscular, :string
  	add_column :clinicals, :aparato_respiratorio, :string
  	add_column :clinicals, :tos, :string
  	add_column :clinicals, :expectoracion, :string
  	add_column :clinicals, :disnea, :string
  	add_column :clinicals, :fuma, :string
  	add_column :clinicals, :cuanto_fuma, :string
  	add_column :clinicals, :roncus, :string
  	add_column :clinicals, :sibilancia, :string
  	add_column :clinicals, :estertores, :string
  	add_column :clinicals, :aparato_digestivo_anexos, :string
  	add_column :clinicals, :intervenciones_quirurgias, :string
  	add_column :clinicals, :aparato_urinario_genital, :string
  	add_column :clinicals, :ciclo_menstruales, :string
  	add_column :clinicals, :aparato_circulatorio_frec_cardiaca, :string
  	add_column :clinicals, :aparato_circulatorio_varices, :string
  	add_column :clinicals, :sistema_nervioso, :string
  	add_column :clinicals, :examen_oftalmologico, :string
  	add_column :clinicals, :examen_otorrinolaringologico, :string
  	add_column :clinicals, :examen_pel, :string
  	add_column :clinicals, :radiografia_torax_abreugrafia, :string
  	add_column :clinicals, :analisis_orina, :string
  	add_column :clinicals, :vdrl, :string
  	add_column :clinicals, :chagas, :string
  	add_column :clinicals, :toxo, :string
  	add_column :clinicals, :parasitologia, :string
  	add_column :clinicals, :glucemia, :string
  	add_column :clinicals, :uremia, :string
  	add_column :clinicals, :uricemia, :string
  	add_column :clinicals, :hamograma, :string
  	add_column :clinicals, :eritrosodimentacion, :string
  	add_column :clinicals, :colesteromia, :string
  	add_column :clinicals, :otros, :string
  	add_column :clinicals, :otros_examenes, :string
  	add_column :clinicals, :conclusion, :string
  	add_column :clinicals, :conclusion_final, :string
  	add_column :clinicals, :profesional_actuante, :string
  end
end
